# Generated by Django 5.1.5 on 2025-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=30)),
            ],
        ),
    ]
