# Generated by Django 5.1.5 on 2025-03-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_reply',
        ),
    ]
