# Generated by Django 5.1.5 on 2025-03-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_post',
        ),
    ]
