# Generated by Django 5.1.5 on 2025-03-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.CharField(max_length=30)),
            ],
        ),
    ]
