# Generated by Django 5.1.5 on 2025-03-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0004_tbl_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_comment',
        ),
    ]
