# Generated by Django 5.1.5 on 2025-03-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0005_delete_tbl_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.CharField(max_length=30)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pet.tbl_post')),
            ],
        ),
    ]
