# Generated by Django 5.1.5 on 2025-03-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Pet', '0008_tbl_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pet')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pet.tbl_post')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
