# Generated by Django 5.1.5 on 2025-03-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0010_tbl_grp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_grp',
        ),
    ]
