# Generated by Django 5.1.5 on 2025-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0011_delete_tbl_grp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_description', models.CharField(max_length=30)),
                ('group_photo', models.FileField(upload_to='Assets/File/user')),
                ('group_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
