# Generated by Django 5.1.5 on 2025-03-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0013_tbl_lostpet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_grp',
        ),
    ]
