# Generated by Django 5.1.5 on 2025-03-13 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Pet', '0016_delete_tbl_lostpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_lostpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lostpet_name', models.CharField(max_length=30)),
                ('lostpet_description', models.CharField(max_length=30)),
                ('lostpet_photo', models.FileField(upload_to='Assets/File/user')),
                ('lostpet_date', models.DateField(auto_now_add=True)),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pet')),
            ],
        ),
    ]
