# Generated by Django 5.1.5 on 2025-03-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Pet', '0017_tbl_lostpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_grpmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpmember_status', models.IntegerField(default=0)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pet')),
            ],
        ),
    ]
