# Generated by Django 5.1.5 on 2025-03-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0020_tbl_grpmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_lostpet',
            name='lostpet_status',
            field=models.IntegerField(default=0),
        ),
    ]
