# Generated by Django 5.1.5 on 2025-03-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0021_tbl_lostpet_lostpet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_grpmembers',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pet.tbl_grp'),
        ),
    ]
