# Generated by Django 5.1.5 on 2025-03-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Pet', '0025_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_content', models.CharField(max_length=30)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('reply', models.CharField(max_length=30)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pet')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
