# Generated by Django 5.1.5 on 2025-03-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0026_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
