# Generated by Django 5.2 on 2025-04-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0031_tbl_chat_tbl_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_comment',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='tbl_like',
            name='shop',
        ),
    ]
