# Generated by Django 5.2 on 2025-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0032_remove_tbl_comment_shop_remove_tbl_like_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_comment',
            name='comment_date',
            field=models.DateTimeField(),
        ),
    ]
