# Generated by Django 5.2 on 2025-04-11 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0033_alter_tbl_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pet.tbl_post'),
        ),
    ]
