# Generated by Django 5.2 on 2025-04-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Pet', '0035_tbl_gropuchat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_gropuchat',
            new_name='tbl_groupchat',
        ),
    ]
