# Generated by Django 5.2 on 2025-04-16 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0036_rename_tbl_gropuchat_tbl_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_groupchat',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pet.tbl_grp'),
        ),
    ]
