# Generated by Django 5.2 on 2025-04-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Pet', '0037_tbl_groupchat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat',
            name='shop_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_from', to='Guest.tbl_shop'),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='shop_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_to', to='Guest.tbl_shop'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_pet'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_pet'),
        ),
    ]
