# Generated by Django 5.1.5 on 2025-03-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
