# Generated by Django 5.1.5 on 2025-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0002_delete_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/File/user')),
                ('product_price', models.CharField(max_length=30)),
            ],
        ),
    ]
