# Generated by Django 5.2 on 2025-04-17 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Shop', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='shop',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop'),
            preserve_default=False,
        ),
    ]
