# Generated by Django 5.2 on 2025-04-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_tbl_product_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
