# Generated by Django 5.2 on 2025-04-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_delete_tbl_doctor'),
        ('Shop', '0005_delete_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/File/user')),
                ('product_price', models.CharField(max_length=30)),
                ('product_postdate', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
