# Generated by Django 5.1.4 on 2025-02-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_email', models.CharField(max_length=30)),
                ('shop_contact', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('shop_password', models.CharField(max_length=30)),
                ('shop_photo', models.FileField(upload_to='Assets/File/user')),
                ('shop_proof', models.FileField(upload_to='Assets/File?user')),
                ('shop_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
