# Generated by Django 5.1.5 on 2025-02-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_proof',
            field=models.FileField(upload_to='Assets/File/user'),
        ),
    ]
