# Generated by Django 5.1.5 on 2025-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_shop_shop_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('doctor_email', models.CharField(max_length=30)),
                ('doctor_contact', models.CharField(max_length=30)),
                ('doctor_address', models.CharField(max_length=30)),
                ('doctor_photo', models.FileField(upload_to='Assets/File/doctor')),
                ('doctor_password', models.CharField(max_length=30)),
            ],
        ),
    ]
