# Generated by Django 5.1.5 on 2025-03-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_breed'),
        ('Guest', '0003_tbl_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('pet_photo', models.FileField(upload_to='Assets/File/user')),
                ('pet_email', models.CharField(max_length=30)),
                ('pet_password', models.CharField(max_length=30)),
                ('pet_dob', models.DateField()),
                ('pet_bio', models.CharField(max_length=30)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_breed')),
            ],
        ),
    ]
