# Generated by Django 5.1.5 on 2025-03-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_doctor',
        ),
    ]
